export interface Hotel {
  id: string
  name: string
  city: string
  location: string
  address: string
  rating: number
  reviewCount: number
  price: number
  stars: number
  image: string
  images: string[]
  description: string
  amenities: string[]
  coordinates: {
    lat: number
    lng: number
  }
}

export const hotels: Hotel[] = [
  // Warsaw Hotels
  {
    id: "1",
    name: "Hotel Bristol Warsaw",
    city: "Warszawa",
    location: "Śródmieście",
    address: "ul. Krakowskie Przedmieście 42/44, 00-325 Warszawa",
    rating: 4.8,
    reviewCount: 892,
    price: 650,
    stars: 5,
    image: "/images/hotels/hotel-1.jpg",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Luksusowy hotel w sercu Warszawy, oferujący eleganckie pokoje i światowej klasy obsługę. Idealny dla wymagających gości.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h", "Basen"],
    coordinates: { lat: 52.2397, lng: 21.0122 },
  },
  {
    id: "2",
    name: "Novotel Warszawa Centrum",
    city: "Warszawa",
    location: "Centrum",
    address: "ul. Marszałkowska 94/98, 00-510 Warszawa",
    rating: 4.5,
    reviewCount: 1243,
    price: 420,
    stars: 4,
    image: "/images/hotels/hotel-2.jpg",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Nowoczesny hotel w centrum Warszawy z doskonałym dojazdem do głównych atrakcji. Idealny dla biznesu i turystyki.",
    amenities: ["Darmowe WiFi", "Parking", "Restauracja", "Bar", "Klimatyzacja", "Recepcja 24h", "Sale konferencyjne"],
    coordinates: { lat: 52.2297, lng: 21.0122 },
  },
  {
    id: "3",
    name: "Hampton by Hilton Warsaw City Centre",
    city: "Warszawa",
    location: "Wola",
    address: "ul. Wronia 45, 00-870 Warszawa",
    rating: 4.4,
    reviewCount: 678,
    price: 380,
    stars: 3,
    image: "/images/hotels/hotel-3.jpg",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Komfortowy hotel sieci Hilton z doskonałą lokalizacją i świetnym śniadaniem wliczonym w cenę.",
    amenities: ["Darmowe WiFi", "Śniadanie", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 52.2319, lng: 20.9919 },
  },
  {
    id: "4",
    name: "Ibis Warszawa Stare Miasto",
    city: "Warszawa",
    location: "Stare Miasto",
    address: "ul. Muranowska 2, 00-209 Warszawa",
    rating: 4.2,
    reviewCount: 534,
    price: 280,
    stars: 3,
    image: "/images/hotels/hotel-4.jpg",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Przystępny cenowo hotel blisko Starego Miasta. Doskonały wybór dla turystów szukających dobrego stosunku jakości do ceny.",
    amenities: ["Darmowe WiFi", "Bar", "Parking", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 52.2508, lng: 20.9989 },
  },
  // Krakow Hotels
  {
    id: "5",
    name: "Hotel Stary Kraków",
    city: "Kraków",
    location: "Stare Miasto",
    address: "ul. Szczepańska 5, 31-011 Kraków",
    rating: 4.9,
    reviewCount: 1456,
    price: 720,
    stars: 5,
    image: "/images/hotels/hotel-5.jpg",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Ekskluzywny butikowy hotel w zabytkowej kamienicy na Rynku Głównym. Połączenie historii z luksusem.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h", "Basen"],
    coordinates: { lat: 50.0614, lng: 19.9366 },
  },
  {
    id: "6",
    name: "Radisson Blu Hotel Kraków",
    city: "Kraków",
    location: "Centrum",
    address: "ul. Straszewskiego 17, 31-101 Kraków",
    rating: 4.6,
    reviewCount: 987,
    price: 480,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Stylowy hotel w centrum Krakowa, kilka kroków od Rynku Głównego. Idealne miejsce dla biznesu i wypoczynku.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 50.0599, lng: 19.9344 },
  },
  {
    id: "7",
    name: "Hotel Wielopole",
    city: "Kraków",
    location: "Kazimierz",
    address: "ul. Wielopole 3, 31-072 Kraków",
    rating: 4.3,
    reviewCount: 445,
    price: 340,
    stars: 3,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Kameralny hotel w pobliżu Kazimierza. Przytulna atmosfera i osobista obsługa.",
    amenities: ["Darmowe WiFi", "Śniadanie", "Parking", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 50.0547, lng: 19.9449 },
  },
  {
    id: "8",
    name: "Campanile Kraków",
    city: "Kraków",
    location: "Podgórze",
    address: "ul. Życzkowskiego 16, 31-864 Kraków",
    rating: 4.1,
    reviewCount: 312,
    price: 260,
    stars: 3,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Przystępny cenowo hotel z dobrym dojazdem do centrum. Idealne miejsce dla rodzin.",
    amenities: ["Darmowe WiFi", "Parking", "Restauracja", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 50.0343, lng: 19.9498 },
  },
  // Gdansk Hotels
  {
    id: "9",
    name: "Hilton Gdańsk",
    city: "Gdańsk",
    location: "Śródmieście",
    address: "ul. Targ Rybny 1, 80-838 Gdańsk",
    rating: 4.7,
    reviewCount: 1123,
    price: 580,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Luksusowy hotel nad Motławą z widokiem na Stare Miasto. Połączenie nowoczesności z historycznym otoczeniem.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h", "Basen"],
    coordinates: { lat: 54.352, lng: 18.6466 },
  },
  {
    id: "10",
    name: "Radisson Hotel & Suites Gdańsk",
    city: "Gdańsk",
    location: "Wrzeszcz",
    address: "ul. Henryka Pobożnego 2, 80-855 Gdańsk",
    rating: 4.5,
    reviewCount: 789,
    price: 420,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Nowoczesny hotel z przestronnymi apartamentami. Doskonała lokalizacja blisko centrum handlowego.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 54.3776, lng: 18.6105 },
  },
  {
    id: "11",
    name: "Hotel Gdańsk Boutique",
    city: "Gdańsk",
    location: "Stare Miasto",
    address: "ul. Heweliusza 22, 80-890 Gdańsk",
    rating: 4.4,
    reviewCount: 567,
    price: 380,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Stylowy butikowy hotel w sercu Starego Miasta. Unikalny design i doskonała obsługa.",
    amenities: ["Darmowe WiFi", "Śniadanie", "Bar", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 54.3488, lng: 18.6539 },
  },
  // Wroclaw Hotels
  {
    id: "12",
    name: "The Granary - La Suite Hotel",
    city: "Wrocław",
    location: "Ostrów Tumski",
    address: "ul. Mennicza 24, 50-057 Wrocław",
    rating: 4.8,
    reviewCount: 934,
    price: 620,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Ekskluzywny hotel w zabytkowym spichlerzu na Ostrowie Tumskim. Wyjątkowa atmosfera i najwyższy standard.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h"],
    coordinates: { lat: 51.1145, lng: 17.0445 },
  },
  {
    id: "13",
    name: "DoubleTree by Hilton Wrocław",
    city: "Wrocław",
    location: "Centrum",
    address: "ul. Podwale 84, 50-414 Wrocław",
    rating: 4.6,
    reviewCount: 876,
    price: 460,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Nowoczesny hotel w centrum Wrocławia. Idealne miejsce dla gości biznesowych i turystów.",
    amenities: [
      "Darmowe WiFi",
      "Restauracja",
      "Bar",
      "Parking",
      "Siłownia",
      "Klimatyzacja",
      "Recepcja 24h",
      "Sale konferencyjne",
    ],
    coordinates: { lat: 51.1079, lng: 17.0385 },
  },
  {
    id: "14",
    name: "Puro Wrocław Stare Miasto",
    city: "Wrocław",
    location: "Stare Miasto",
    address: "ul. Włodkowica 6, 50-072 Wrocław",
    rating: 4.5,
    reviewCount: 654,
    price: 390,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Designerski hotel w centrum Wrocławia. Nowoczesny styl i świetna lokalizacja.",
    amenities: ["Darmowe WiFi", "Bar", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 51.1089, lng: 17.0326 },
  },
  // Poznan Hotels
  {
    id: "15",
    name: "Sheraton Poznań Hotel",
    city: "Poznań",
    location: "Centrum",
    address: "ul. Bukowska 3/9, 60-809 Poznań",
    rating: 4.6,
    reviewCount: 1045,
    price: 520,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Luksusowy hotel w centrum Poznania z doskonałymi udogodnieniami. Idealne miejsce dla wymagających gości.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h", "Basen"],
    coordinates: { lat: 52.4064, lng: 16.9252 },
  },
  {
    id: "16",
    name: "IBB Andersia Hotel",
    city: "Poznań",
    location: "Centrum",
    address: "plac Andersa 3, 61-894 Poznań",
    rating: 4.5,
    reviewCount: 723,
    price: 440,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Nowoczesny hotel w wieżowcu z panoramicznym widokiem na miasto. Doskonała lokalizacja przy centrum handlowym.",
    amenities: [
      "Darmowe WiFi",
      "Spa & Wellness",
      "Restauracja",
      "Bar",
      "Parking",
      "Siłownia",
      "Klimatyzacja",
      "Recepcja 24h",
    ],
    coordinates: { lat: 52.4048, lng: 16.9299 },
  },
  {
    id: "17",
    name: "Hotel Blow Up Hall 5050",
    city: "Poznań",
    location: "Jeżyce",
    address: "ul. Kościelna 43, 60-537 Poznań",
    rating: 4.4,
    reviewCount: 489,
    price: 360,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Artystyczny hotel z unikalnym designem. Każdy pokój to dzieło sztuki. Idealne dla miłośników nietypowych miejsc.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 52.4167, lng: 16.9167 },
  },
  // Zakopane Hotels
  {
    id: "18",
    name: "Grand Hotel Stamary",
    city: "Zakopane",
    location: "Centrum",
    address: "ul. Kościuszki 19, 34-500 Zakopane",
    rating: 4.7,
    reviewCount: 856,
    price: 550,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Luksusowy hotel w sercu Zakopanego z widokiem na Tatry. Połączenie tradycji góralskiej z nowoczesnym komfortem.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h", "Basen"],
    coordinates: { lat: 49.2992, lng: 19.9496 },
  },
  {
    id: "19",
    name: "Hotel Mercure Zakopane Kasprowy",
    city: "Zakopane",
    location: "Kuźnice",
    address: "ul. Szymaszkowa 6, 34-500 Zakopane",
    rating: 4.5,
    reviewCount: 634,
    price: 420,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Nowoczesny hotel u podnóża Kasprowego Wierchu. Idealna baza wypadowa dla narciarzy i turystów górskich.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h", "Basen"],
    coordinates: { lat: 49.2764, lng: 19.9379 },
  },
  {
    id: "20",
    name: "Nosalowy Dwór Resort & Spa",
    city: "Zakopane",
    location: "Nosalowa",
    address: "ul. Balzera 21d, 34-500 Zakopane",
    rating: 4.6,
    reviewCount: 712,
    price: 480,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Ekskluzywny resort spa w stylu góralskim. Doskonałe miejsce na relaks z widokiem na Tatry.",
    amenities: [
      "Darmowe WiFi",
      "Spa & Wellness",
      "Restauracja",
      "Bar",
      "Parking",
      "Siłownia",
      "Recepcja 24h",
      "Basen",
      "Sauna",
    ],
    coordinates: { lat: 49.2856, lng: 19.9812 },
  },
  // Lublin Hotels
  {
    id: "21",
    name: "Hotel Mercure Lublin Centrum",
    city: "Lublin",
    location: "Centrum Lublina",
    address: "ul. Królewska 12, 20-109 Lublin",
    rating: 4.5,
    reviewCount: 342,
    price: 320,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Nowoczesny hotel w centrum Lublina, oferujący komfortowe pokoje z widokiem na Stare Miasto.",
    amenities: ["Darmowe WiFi", "Parking", "Restauracja", "Bar", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 51.2465, lng: 22.5684 },
  },
  {
    id: "22",
    name: "Grand Hotel Lublinianka",
    city: "Lublin",
    location: "Stare Miasto",
    address: "ul. Krakowskie Przedmieście 56, 20-002 Lublin",
    rating: 4.7,
    reviewCount: 528,
    price: 450,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Luksusowy hotel w zabytkowym budynku na Starym Mieście. Oferuje eleganckie pokoje i spa.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h"],
    coordinates: { lat: 51.2477, lng: 22.5683 },
  },
  {
    id: "23",
    name: "Hotel Vanilla",
    city: "Lublin",
    location: "Śródmieście",
    address: "ul. Spokójna 8, 20-074 Lublin",
    rating: 4.3,
    reviewCount: 215,
    price: 280,
    stars: 3,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Butikowy hotel o nowoczesnym designie. Doskonały stosunek jakości do ceny.",
    amenities: ["Darmowe WiFi", "Śniadanie", "Parking", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 51.2432, lng: 22.5598 },
  },
  // Sopot Hotels
  {
    id: "24",
    name: "Sheraton Sopot Hotel",
    city: "Sopot",
    location: "Plaża",
    address: "ul. Powstańców Warszawy 10, 81-718 Sopot",
    rating: 4.8,
    reviewCount: 1234,
    price: 680,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Luksusowy hotel nad samym morzem w Sopocie. Widok na plażę i molo z każdego pokoju.",
    amenities: [
      "Darmowe WiFi",
      "Spa & Wellness",
      "Restauracja",
      "Bar",
      "Parking",
      "Siłownia",
      "Recepcja 24h",
      "Basen",
      "Plaża prywatna",
    ],
    coordinates: { lat: 54.4419, lng: 18.5602 },
  },
  {
    id: "25",
    name: "Molo Hotel",
    city: "Sopot",
    location: "Centrum",
    address: "ul. Bohaterów Monte Cassino 53, 81-759 Sopot",
    rating: 4.6,
    reviewCount: 789,
    price: 520,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Stylowy hotel na słynnym deptaku Monte Cassino. Blisko mola i plaży.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 54.4428, lng: 18.5647 },
  },
  // Torun Hotels
  {
    id: "26",
    name: "Hotel Copernicus Toruń",
    city: "Toruń",
    location: "Stare Miasto",
    address: "ul. Bulwar Filadelfijski 11, 87-100 Toruń",
    rating: 4.7,
    reviewCount: 645,
    price: 420,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Elegancki hotel nad Wisłą z widokiem na Stare Miasto. Połączenie historii z nowoczesnością.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h", "Basen"],
    coordinates: { lat: 53.0138, lng: 18.6048 },
  },
  {
    id: "27",
    name: "Hotel Petite Fleur",
    city: "Toruń",
    location: "Centrum",
    address: "ul. Piekary 25, 87-100 Toruń",
    rating: 4.5,
    reviewCount: 423,
    price: 340,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Kameralny hotel w zabytkowej kamienicy. Wyjątkowy klimat i doskonała lokalizacja.",
    amenities: ["Darmowe WiFi", "Śniadanie", "Restauracja", "Bar", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 53.0103, lng: 18.6048 },
  },
  // Katowice Hotels
  {
    id: "28",
    name: "Hotel Monopol Katowice",
    city: "Katowice",
    location: "Centrum",
    address: "ul. Dworcowa 5, 40-012 Katowice",
    rating: 4.6,
    reviewCount: 876,
    price: 480,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Zabytkowy hotel z 1902 roku w centrum Katowic. Połączenie historii z luksusem.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h"],
    coordinates: { lat: 50.2599, lng: 19.0216 },
  },
  {
    id: "29",
    name: "Vienna House Katowice",
    city: "Katowice",
    location: "Śródmieście",
    address: "ul. Uniwersytecka 13, 40-007 Katowice",
    rating: 4.4,
    reviewCount: 567,
    price: 380,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Nowoczesny hotel w centrum Katowic. Idealne miejsce dla gości biznesowych.",
    amenities: [
      "Darmowe WiFi",
      "Restauracja",
      "Bar",
      "Parking",
      "Siłownia",
      "Klimatyzacja",
      "Recepcja 24h",
      "Sale konferencyjne",
    ],
    coordinates: { lat: 50.2649, lng: 19.0238 },
  },
  // Lodz Hotels
  {
    id: "30",
    name: "Vienna House Andel's Łódź",
    city: "Łódź",
    location: "Centrum",
    address: "ul. Ogrodowa 17, 91-065 Łódź",
    rating: 4.7,
    reviewCount: 923,
    price: 440,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Designerski hotel w centrum Łodzi. Nowoczesna architektura i doskonałe udogodnienia.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h", "Basen"],
    coordinates: { lat: 51.7687, lng: 19.4569 },
  },
  // Szczecin Hotels
  {
    id: "31",
    name: "Radisson Blu Szczecin",
    city: "Szczecin",
    location: "Centrum",
    address: "ul. Plac Rodła 10, 70-419 Szczecin",
    rating: 4.6,
    reviewCount: 734,
    price: 460,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Nowoczesny hotel w centrum Szczecina z widokiem na Odrę. Doskonała lokalizacja dla biznesu i turystyki.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h", "Basen"],
    coordinates: { lat: 53.4285, lng: 14.5528 },
  },
  {
    id: "32",
    name: "Hotel Vulcan",
    city: "Szczecin",
    location: "Stare Miasto",
    address: "ul. Staromłyńska 1, 70-561 Szczecin",
    rating: 4.4,
    reviewCount: 456,
    price: 350,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Butikowy hotel w zabytkowej części Szczecina. Unikalny charakter i doskonała obsługa.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 53.4289, lng: 14.5553 },
  },
  // Bydgoszcz Hotels
  {
    id: "33",
    name: "Hotel City Bydgoszcz",
    city: "Bydgoszcz",
    location: "Centrum",
    address: "ul. Jagiellońska 59, 85-097 Bydgoszcz",
    rating: 4.5,
    reviewCount: 623,
    price: 380,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Nowoczesny hotel w centrum Bydgoszczy. Idealne miejsce dla gości biznesowych i turystów.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h"],
    coordinates: { lat: 53.1235, lng: 18.0084 },
  },
  {
    id: "34",
    name: "Focus Hotel Premium Bydgoszcz",
    city: "Bydgoszcz",
    location: "Śródmieście",
    address: "ul. Dworcowa 94, 85-009 Bydgoszcz",
    rating: 4.3,
    reviewCount: 412,
    price: 310,
    stars: 3,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Komfortowy hotel blisko dworca. Doskonały wybór dla podróżnych biznesowych.",
    amenities: ["Darmowe WiFi", "Restauracja", "Parking", "Klimatyzacja", "Recepcja 24h", "Sale konferencyjne"],
    coordinates: { lat: 53.1325, lng: 18.0084 },
  },
  // Białystok Hotels
  {
    id: "35",
    name: "Hotel Branicki",
    city: "Białystok",
    location: "Centrum",
    address: "ul. Zwycięstwa 1, 15-703 Białystok",
    rating: 4.6,
    reviewCount: 567,
    price: 420,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Elegancki hotel w centrum Białegostoku. Wysoki standard i doskonała lokalizacja.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h"],
    coordinates: { lat: 53.1325, lng: 23.1688 },
  },
  {
    id: "36",
    name: "Hotel Gołębiewski Białystok",
    city: "Białystok",
    location: "Dojlidy",
    address: "ul. Aleja Jana Pawła II 1, 15-703 Białystok",
    rating: 4.7,
    reviewCount: 892,
    price: 480,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Kompleks hotelowy z aquaparkiem i spa. Idealne miejsce dla rodzin.",
    amenities: [
      "Darmowe WiFi",
      "Spa & Wellness",
      "Restauracja",
      "Bar",
      "Parking",
      "Siłownia",
      "Recepcja 24h",
      "Basen",
      "Aquapark",
    ],
    coordinates: { lat: 53.1425, lng: 23.1788 },
  },
  // Rzeszów Hotels
  {
    id: "37",
    name: "Grand Hotel Boutique Rzeszów",
    city: "Rzeszów",
    location: "Centrum",
    address: "ul. Dymnickiego 1, 35-030 Rzeszów",
    rating: 4.7,
    reviewCount: 645,
    price: 450,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Luksusowy butikowy hotel w centrum Rzeszowa. Elegancja i wysoki standard obsługi.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h"],
    coordinates: { lat: 50.0413, lng: 21.9991 },
  },
  {
    id: "38",
    name: "Hotel Rzeszów",
    city: "Rzeszów",
    location: "Śródmieście",
    address: "ul. Grunwaldzka 16, 35-959 Rzeszów",
    rating: 4.4,
    reviewCount: 478,
    price: 340,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Nowoczesny hotel w centrum miasta. Doskonały wybór dla gości biznesowych.",
    amenities: [
      "Darmowe WiFi",
      "Restauracja",
      "Bar",
      "Parking",
      "Siłownia",
      "Klimatyzacja",
      "Recepcja 24h",
      "Sale konferencyjne",
    ],
    coordinates: { lat: 50.0413, lng: 22.0091 },
  },
  // Olsztyn Hotels
  {
    id: "39",
    name: "Hotel Warmiński",
    city: "Olsztyn",
    location: "Centrum",
    address: "ul. Kołobrzeska 1, 10-001 Olsztyn",
    rating: 4.5,
    reviewCount: 534,
    price: 380,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Komfortowy hotel w centrum Olsztyna. Idealna lokalizacja dla zwiedzających Warmię i Mazury.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 53.7784, lng: 20.4801 },
  },
  {
    id: "40",
    name: "Hotel Kur Spa Mikołajki",
    city: "Mikołajki",
    location: "Nad jeziorem",
    address: "ul. Kolejowa 8, 11-730 Mikołajki",
    rating: 4.8,
    reviewCount: 923,
    price: 520,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Luksusowy resort spa nad jeziorem w Mikołajkach. Idealne miejsce na relaks.",
    amenities: [
      "Darmowe WiFi",
      "Spa & Wellness",
      "Restauracja",
      "Bar",
      "Parking",
      "Siłownia",
      "Recepcja 24h",
      "Basen",
      "Plaża prywatna",
    ],
    coordinates: { lat: 53.8025, lng: 21.5703 },
  },
  // Kielce Hotels
  {
    id: "41",
    name: "Hotel Binkowski",
    city: "Kielce",
    location: "Centrum",
    address: "ul. Sienkiewicza 16, 25-007 Kielce",
    rating: 4.5,
    reviewCount: 456,
    price: 360,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Elegancki hotel w centrum Kielc. Doskonała lokalizacja i wysoki standard.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 50.8661, lng: 20.6286 },
  },
  {
    id: "42",
    name: "Hotel Dal",
    city: "Kielce",
    location: "Śródmieście",
    address: "ul. Paderewskiego 28, 25-950 Kielce",
    rating: 4.3,
    reviewCount: 312,
    price: 290,
    stars: 3,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Przystępny cenowo hotel w Kielcach. Dobry stosunek jakości do ceny.",
    amenities: ["Darmowe WiFi", "Parking", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 50.8761, lng: 20.6386 },
  },
  // Zielona Góra Hotels
  {
    id: "43",
    name: "Qubus Hotel Zielona Góra",
    city: "Zielona Góra",
    location: "Centrum",
    address: "ul. Zawadzkiego 1, 65-043 Zielona Góra",
    rating: 4.6,
    reviewCount: 589,
    price: 410,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Nowoczesny hotel w centrum Zielonej Góry. Wysoki standard i doskonałe udogodnienia.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h"],
    coordinates: { lat: 51.9356, lng: 15.5062 },
  },
  // Opole Hotels
  {
    id: "44",
    name: "Hotel Weneda",
    city: "Opole",
    location: "Centrum",
    address: "ul. Krakowska 11, 45-075 Opole",
    rating: 4.4,
    reviewCount: 423,
    price: 340,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Komfortowy hotel w centrum Opola. Idealne miejsce dla gości biznesowych i turystów.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 50.6751, lng: 17.9213 },
  },
  // Gliwice Hotels
  {
    id: "45",
    name: "Hotel Diament Plaza Gliwice",
    city: "Gliwice",
    location: "Centrum",
    address: "ul. Zwycięstwa 30, 44-100 Gliwice",
    rating: 4.5,
    reviewCount: 678,
    price: 390,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Nowoczesny hotel w centrum Gliwic. Doskonała lokalizacja i wysoki standard.",
    amenities: ["Darmowe WiFi", "Spa & Wellness", "Restauracja", "Bar", "Parking", "Siłownia", "Recepcja 24h"],
    coordinates: { lat: 50.2945, lng: 18.6714 },
  },
  // Częstochowa Hotels
  {
    id: "46",
    name: "Hotel Mercure Częstochowa Centrum",
    city: "Częstochowa",
    location: "Centrum",
    address: "ul. Katedralna 3, 42-200 Częstochowa",
    rating: 4.6,
    reviewCount: 734,
    price: 420,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "Elegancki hotel w centrum Częstochowy, blisko Jasnej Góry. Idealne miejsce dla pielgrzymów i turystów.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 50.8118, lng: 19.1203 },
  },
  {
    id: "47",
    name: "Hotel Arche",
    city: "Częstochowa",
    location: "Jasna Góra",
    address: "ul. Kordeckiego 1, 42-225 Częstochowa",
    rating: 4.4,
    reviewCount: 512,
    price: 350,
    stars: 3,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Hotel przy Jasnej Górze. Idealne miejsce dla pielgrzymów.",
    amenities: ["Darmowe WiFi", "Restauracja", "Parking", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 50.8218, lng: 19.0903 },
  },
  // Radom Hotels
  {
    id: "48",
    name: "Hotel Gromada Radom",
    city: "Radom",
    location: "Centrum",
    address: "ul. Traugutta 65, 26-600 Radom",
    rating: 4.3,
    reviewCount: 389,
    price: 310,
    stars: 3,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Komfortowy hotel w centrum Radomia. Dobry wybór dla gości biznesowych.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 51.4027, lng: 21.1471 },
  },
  // Koszalin Hotels
  {
    id: "49",
    name: "Hotel Gromada Koszalin",
    city: "Koszalin",
    location: "Centrum",
    address: "ul. Zwycięstwa 20, 75-037 Koszalin",
    rating: 4.4,
    reviewCount: 456,
    price: 340,
    stars: 4,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Nowoczesny hotel w centrum Koszalina. Blisko morza i głównych atrakcji.",
    amenities: ["Darmowe WiFi", "Restauracja", "Bar", "Parking", "Siłownia", "Klimatyzacja", "Recepcja 24h"],
    coordinates: { lat: 54.1943, lng: 16.1714 },
  },
  // Kołobrzeg Hotels
  {
    id: "50",
    name: "Marine Hotel Kołobrzeg",
    city: "Kołobrzeg",
    location: "Plaża",
    address: "ul. Sułkowskiego 9, 78-100 Kołobrzeg",
    rating: 4.7,
    reviewCount: 892,
    price: 550,
    stars: 5,
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Luksusowy hotel spa nad morzem w Kołobrzegu. Idealne miejsce na relaks i regenerację.",
    amenities: [
      "Darmowe WiFi",
      "Spa & Wellness",
      "Restauracja",
      "Bar",
      "Parking",
      "Siłownia",
      "Recepcja 24h",
      "Basen",
      "Plaża prywatna",
    ],
    coordinates: { lat: 54.1761, lng: 15.5831 },
  },
]

export function getHotelById(id: string): Hotel | undefined {
  return hotels.find((hotel) => hotel.id === id)
}

export function searchHotels(query: string, city?: string): Hotel[] {
  let filtered = hotels

  if (city && city !== "Wszystkie") {
    filtered = filtered.filter((hotel) => hotel.city === city)
  }

  if (!query) return filtered

  const lowerQuery = query.toLowerCase()
  return filtered.filter(
    (hotel) =>
      hotel.name.toLowerCase().includes(lowerQuery) ||
      hotel.location.toLowerCase().includes(lowerQuery) ||
      hotel.address.toLowerCase().includes(lowerQuery) ||
      hotel.city.toLowerCase().includes(lowerQuery),
  )
}

export function getCities(): string[] {
  const cities = Array.from(new Set(hotels.map((hotel) => hotel.city)))
  return cities.sort()
}

export interface FilterOptions {
  city?: string
  minPrice?: number
  maxPrice?: number
  minRating?: number
  stars?: number[]
  amenities?: string[]
}

export function filterHotels(options: FilterOptions): Hotel[] {
  let filtered = hotels

  if (options.city && options.city !== "Wszystkie") {
    filtered = filtered.filter((hotel) => hotel.city === options.city)
  }

  if (options.minPrice !== undefined) {
    filtered = filtered.filter((hotel) => hotel.price >= options.minPrice!)
  }

  if (options.maxPrice !== undefined) {
    filtered = filtered.filter((hotel) => hotel.price <= options.maxPrice!)
  }

  if (options.minRating !== undefined) {
    filtered = filtered.filter((hotel) => hotel.rating >= options.minRating!)
  }

  if (options.stars && options.stars.length > 0) {
    filtered = filtered.filter((hotel) => options.stars!.includes(hotel.stars))
  }

  if (options.amenities && options.amenities.length > 0) {
    filtered = filtered.filter((hotel) => options.amenities!.every((amenity) => hotel.amenities.includes(amenity)))
  }

  return filtered
}

export function getAllAmenities(): string[] {
  const amenitiesSet = new Set<string>()
  hotels.forEach((hotel) => {
    hotel.amenities.forEach((amenity) => amenitiesSet.add(amenity))
  })
  return Array.from(amenitiesSet).sort()
}
